apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "php-bluegreen", "namespace": "",
      "kind": "DeploymentConfig"}]'
  creationTimestamp: 2017-02-01T23:09:54Z
  labels:
    name: php-bluegreen-promote
  name: php-bluegreen-promote
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
        stage 'promote release'
        openshiftTag alias: 'false', apiURL: '', authToken: '', destStream: 'php-bluegreen', destTag: 'current-release', destinationAuthToken: '', destinationNamespace: '', namespace: '', srcStream: 'php-bluegreen', srcTag: 'next-release', verbose: 'false'
        stage 'deploy'
        openshiftDeploy(deploymentConfig: 'php-bluegreen')
        stage 'smoke test: side'
        #
        sh 'curl http://php-bluegreen-devops-demos.int.open.paas.redhat.com/ | grep -i "Welcome to an OpenShift Application version 1.21"'
        sh 'curl http://php-bluegreen-devops-demos.int.open.paas.redhat.com/ | grep -i "Welcome to an OpenShift Application version 1.21"'
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
