apiVersion: v1
kind: BuildConfig
metadata:
  name: php-bluegreen-pipeline
  labels:
    name: php-bluegreen-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "php-bluegreen", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage 'build'\nopenshiftBuild(buildConfig: 'php-bluegreen', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'php-bluegreen')\nopenshiftScale(deploymentConfig: 'php-bluegreen',replicaCount: '2')\n}"
  output:
  resources:
postCommit:
